# Generated by Django 5.0 on 2024-02-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
